[application]
name = "dust"

[web.app]
title = "Dust"

[web.watcher]
watch_path = ["src", "assets", "crates"]

[web.resource]
style = ["assets/styles.css"]
script = []

[web.resource.dev]
script = []
style = []

[bundle]
identifier = "dev.dust.morse"
publisher = "Dust"
